"""Gap E-3 — XML index internal node table.

A PRIMARY XML INDEX creates an internal node table (sysschobjs.type = 'IT').
recover_schema must skip it and return only the user table.
read_table_rows must return the original XML rows without crash.

Fixture: ``xml_index_full.bak``
Generated by: ``python -m tools.fixture_run all-versions --suite xml-index``
"""
from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows


def test_xml_index_no_internal_tables(fixture_bak_xml_index: str) -> None:
    """recover_schema must not expose internal XML node tables as user tables."""
    store = PageStore.from_bak(fixture_bak_xml_index)
    schema = recover_schema(store)

    # All returned tables should be named by their user-table names.
    # Internal XML index node tables have system-generated names like
    # xml_index_nodes_XXXXXX_XXXXXXXX — they must not appear here.
    for tbl in schema.tables:
        assert not tbl.name.startswith("xml_index_nodes_"), (
            f"Internal XML node table {tbl.name!r} must not be in schema"
        )


def test_xml_index_user_table_present(fixture_bak_xml_index: str) -> None:
    from tools.make_xml_index_fixture import TABLE

    store = PageStore.from_bak(fixture_bak_xml_index)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None, f"user table {TABLE!r} not found in schema"


def test_xml_index_row_count(fixture_bak_xml_index: str) -> None:
    from tools.make_xml_index_fixture import ROW_COUNT, TABLE

    store = PageStore.from_bak(fixture_bak_xml_index)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None

    rows = list(read_table_rows(store, tbl))
    assert len(rows) == ROW_COUNT


def test_xml_index_values(fixture_bak_xml_index: str) -> None:
    """Spot-check XML content and tag column values."""
    from tools.make_xml_index_fixture import TABLE

    store = PageStore.from_bak(fixture_bak_xml_index)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None

    rows_by_id = {r["id"]: r for r in read_table_rows(store, tbl)}

    for sample_id in [1, 25, 50, 99, 100]:
        row = rows_by_id.get(sample_id)
        assert row is not None, f"row id={sample_id} missing"
        # tag cycles through 'tag_0'..'tag_4'
        expected_tag = f"tag_{sample_id % 5}"
        assert row["tag"] == expected_tag, f"id={sample_id}: {row['tag']!r}"
        # doc column is XML — must not be None and must mention the id
        doc = row.get("doc")
        assert doc is not None, f"id={sample_id}: doc is None"
        doc_str = doc if isinstance(doc, str) else str(doc)
        assert str(sample_id) in doc_str, f"id={sample_id}: id missing from doc {doc_str!r}"
