"""ARCHIVE CCI type-coverage tests (Gap I-1).

``archive_columnstore_types_full.bak`` — seven 35,000-row tables, one per
dictionary-encoded columnstore type, all under COLUMNSTORE_ARCHIVE compression.

Purpose
-------
Gap I-1 documents that the existing ARCHIVE fixtures only exercise CHAR(10).
All other dictionary-encoded types (VARCHAR, NCHAR, NVARCHAR, BINARY, VARBINARY,
UNIQUEIDENTIFIER) store data in a string pool whose stride or width differs from
CHAR.  A decoder that assumes CHAR's fixed-10-byte pool stride would silently
corrupt every row for the other six types.

Each test is parametrized over ``sequential`` (monotonically-increasing insert
order) and ``random`` (INSERT ORDER BY NEWID()).  A failure on ``[random]`` but
not ``[sequential]`` pinpoints a non-sequential segment decode bug.

Table layout
------------
Each table has the same schema::

    id   INT                NOT NULL
    val  <type-under-test>  NULL

Row count: 35,000 (> 32,767 → forces multi-sub-block enc_type=5 under ARCHIVE).
NULL pattern: every 500th row has val = NULL  → 70 NULLs per table.

Tables
------
    archive_char10       — CHAR(10)         baseline / sanity check
    archive_varchar20    — VARCHAR(20)       variable-length single-byte pool
    archive_nchar10      — NCHAR(10)         fixed UTF-16LE pool (20 bytes/entry)
    archive_nvarchar20   — NVARCHAR(20)      variable-length UTF-16LE pool
    archive_binary10     — BINARY(10)        fixed binary pool
    archive_varbinary20  — VARBINARY(20)     variable-length binary pool
    archive_uuid         — UNIQUEIDENTIFIER  fixed 16-byte pool

Architecture note
-----------------
This fixture was generated by ``tools/make_archive_columnstore_types_fixture.py``,
the first mssqlbak fixture built with the new ``SqlDialect`` / ``EngineAdapter``
layer introduced as the reference pattern for future pgbak/mybak projects.

Fixture generation::

    python -m tools.fixture_run --fixture-dir <dir> archive-columnstore-types
    python -m tools.fixture_run --fixture-dir <dir> archive-columnstore-types-random
    python -m tools.fixture_run all-versions --suite archive-columnstore-types
    python -m tools.fixture_run all-versions --suite archive-columnstore-types-random
"""
from __future__ import annotations

from pathlib import Path

import pytest

from mssqlbak.catalog import recover_schema
from mssqlbak.inspect import classify_table
from mssqlbak.pages import AnyPageStore, PageStore
from mssqlbak.rows import read_table_rows


# ---------------------------------------------------------------------------
# Combined sequential + random fixture (Part II)
# ---------------------------------------------------------------------------

@pytest.fixture(
    params=["sequential", "random"],
    ids=["sequential", "random"],
)
def fixture_bak_types(
    request: pytest.FixtureRequest,
    fixture_bak_archive_columnstore_types: Path,
    fixture_bak_archive_columnstore_types_random: Path,
) -> Path:
    """Parametrized over sequential and random-order variants.

    A test that passes [sequential] but fails [random] pinpoints a
    non-sequential segment decode bug in the ARCHIVE enc=5 decoder.
    """
    if request.param == "random":
        return fixture_bak_archive_columnstore_types_random
    return fixture_bak_archive_columnstore_types

# ---------------------------------------------------------------------------
# Constants that mirror make_archive_columnstore_types_fixture.py
# ---------------------------------------------------------------------------
_TOTAL_ROWS = 35_000
_NULL_EVERY = 500
_NULL_COUNT = _TOTAL_ROWS // _NULL_EVERY   # 70
_NON_NULL_COUNT = _TOTAL_ROWS - _NULL_COUNT  # 34,930

# (table_name, canonical, description)
_ALL_TABLES: tuple[tuple[str, str, str], ...] = (
    ("archive_char10",      "char",       "CHAR(10) — baseline fixed single-byte pool"),
    ("archive_varchar20",   "varchar",    "VARCHAR(20) — variable-length single-byte pool"),
    ("archive_nchar10",     "nchar",      "NCHAR(10) — fixed UTF-16LE pool"),
    ("archive_nvarchar20",  "nvarchar",   "NVARCHAR(20) — variable-length UTF-16LE pool"),
    ("archive_binary10",    "binary",     "BINARY(10) — fixed binary pool"),
    ("archive_varbinary20", "varbinary",  "VARBINARY(20) — variable-length binary pool"),
    ("archive_uuid",        "uuid",       "UNIQUEIDENTIFIER — fixed 16-byte pool"),
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _page_store(fixture_bak: Path) -> AnyPageStore:
    return PageStore.from_bak(fixture_bak)


def _rows(fixture_bak: Path, table: str) -> list[dict]:
    store = _page_store(fixture_bak)
    schema = recover_schema(store)
    tbl = next(t for t in schema.tables if t.name == table)
    return list(read_table_rows(store, tbl, schema.obj_to_name))


def _null_count(rows: list[dict], col: str) -> int:
    return sum(1 for r in rows if r.get(col) is None)


def _non_null_count(rows: list[dict], col: str) -> int:
    return sum(1 for r in rows if r.get(col) is not None)


# ---------------------------------------------------------------------------
# Fixture presence / schema
# ---------------------------------------------------------------------------

def test_fixture_contains_all_tables(
    fixture_bak_types: Path,
) -> None:
    """All seven type tables are present in the backup."""
    schema = recover_schema(_page_store(fixture_bak_types))
    table_names = {t.name for t in schema.tables}
    expected = {tbl for tbl, _, _ in _ALL_TABLES}
    assert expected.issubset(table_names), (
        f"missing tables: {expected - table_names}"
    )


@pytest.mark.parametrize("table,canonical,desc", _ALL_TABLES)
def test_table_classified_as_supported(
    fixture_bak_types: Path,
    table: str,
    canonical: str,
    desc: str,
) -> None:
    """Each table is classified as supported (CCI is readable by the parser)."""
    schema = recover_schema(_page_store(fixture_bak_types))
    tbl_meta = next(t for t in schema.tables if t.name == table)
    result = classify_table(tbl_meta)
    assert result.supported, (
        f"{table} ({canonical}): expected supported, got reason={result.reason!r}"
    )


# ---------------------------------------------------------------------------
# Row counts — primary correctness guard
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("table,canonical,desc", _ALL_TABLES)
def test_total_row_count(
    fixture_bak_types: Path,
    table: str,
    canonical: str,
    desc: str,
) -> None:
    """Each type table decodes to exactly TOTAL_ROWS rows."""
    rows = _rows(fixture_bak_types, table)
    assert len(rows) == _TOTAL_ROWS, (
        f"{table} ({canonical}): expected {_TOTAL_ROWS} rows, got {len(rows)}"
    )


# ---------------------------------------------------------------------------
# NULL counts — enc_type=5 pool correctness
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("table,canonical,desc", _ALL_TABLES)
def test_null_count(
    fixture_bak_types: Path,
    table: str,
    canonical: str,
    desc: str,
) -> None:
    """val column has exactly NULL_COUNT NULLs — verifies pool offset decoding.

    A decoder that misreads the pool stride produces wrong offsets; rows that
    should be non-NULL appear as NULL (or crash).  The exact count is the
    regression guard.
    """
    rows = _rows(fixture_bak_types, table)
    n = _null_count(rows, "val")
    assert n == _NULL_COUNT, (
        f"{table} ({canonical}): expected {_NULL_COUNT} NULLs, got {n}"
    )


@pytest.mark.parametrize("table,canonical,desc", _ALL_TABLES)
def test_non_null_count(
    fixture_bak_types: Path,
    table: str,
    canonical: str,
    desc: str,
) -> None:
    """val column has exactly NON_NULL_COUNT non-NULL values."""
    rows = _rows(fixture_bak_types, table)
    n = _non_null_count(rows, "val")
    assert n == _NON_NULL_COUNT, (
        f"{table} ({canonical}): expected {_NON_NULL_COUNT} non-NULLs, got {n}"
    )


# ---------------------------------------------------------------------------
# Value-type sanity checks — ensure decoded Python type is sensible
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("table,canonical,desc", [
    t for t in _ALL_TABLES if t[1] in ("char", "varchar", "nchar", "nvarchar")
])
def test_string_values_are_str(
    fixture_bak_types: Path,
    table: str,
    canonical: str,
    desc: str,
) -> None:
    """String-type columns decode to Python str (not bytes or None for non-NULL rows)."""
    rows = _rows(fixture_bak_types, table)
    non_null = [r["val"] for r in rows if r.get("val") is not None]
    assert non_null, f"{table}: no non-NULL values found"
    bad = [v for v in non_null[:100] if not isinstance(v, str)]
    assert not bad, (
        f"{table} ({canonical}): expected str values, got {type(bad[0]).__name__!r}"
    )


@pytest.mark.parametrize("table,canonical,desc", [
    t for t in _ALL_TABLES if t[1] in ("binary", "varbinary")
])
def test_binary_values_are_bytes(
    fixture_bak_types: Path,
    table: str,
    canonical: str,
    desc: str,
) -> None:
    """Binary-type columns decode to Python bytes (not str or None for non-NULL rows)."""
    rows = _rows(fixture_bak_types, table)
    non_null = [r["val"] for r in rows if r.get("val") is not None]
    assert non_null, f"{table}: no non-NULL values found"
    bad = [v for v in non_null[:100] if not isinstance(v, (bytes, bytearray))]
    assert not bad, (
        f"{table} ({canonical}): expected bytes values, got {type(bad[0]).__name__!r}"
    )


@pytest.mark.parametrize("table,canonical,desc", [
    t for t in _ALL_TABLES if t[1] == "uuid"
])
def test_uuid_values_are_uuid(
    fixture_bak_types: Path,
    table: str,
    canonical: str,
    desc: str,
) -> None:
    """UNIQUEIDENTIFIER column decodes to UUID objects (not str or bytes)."""
    from uuid import UUID

    rows = _rows(fixture_bak_types, table)
    non_null = [r["val"] for r in rows if r.get("val") is not None]
    assert non_null, f"{table}: no non-NULL values found"
    bad = [v for v in non_null[:100] if not isinstance(v, UUID)]
    assert not bad, (
        f"{table} ({canonical}): expected UUID values, got {type(bad[0]).__name__!r}"
    )


# ---------------------------------------------------------------------------
# Cross-type consistency — all tables should agree on total + NULL counts
# ---------------------------------------------------------------------------

def test_all_types_agree_on_null_count(
    fixture_bak_types: Path,
) -> None:
    """All seven type tables produce the same NULL count.

    If any type's pool decoder is broken, its NULL count will diverge from
    the others.  This test surfaces that divergence in one place.
    """
    counts: dict[str, int] = {}
    for table, canonical, _ in _ALL_TABLES:
        rows = _rows(fixture_bak_types, table)
        counts[f"{table} ({canonical})"] = _null_count(rows, "val")

    wrong = {k: v for k, v in counts.items() if v != _NULL_COUNT}
    assert not wrong, (
        f"NULL count mismatch — expected {_NULL_COUNT} for all types:\n"
        + "\n".join(f"  {k}: {v}" for k, v in wrong.items())
    )
