"""Covering index (NC with INCLUDE) coverage tests (Gap E-1).

Validates that a nonclustered index with included columns does not interfere
with mssqlbak's base-table extraction.

Fixture
-------
``covering_index_full.bak`` — generated by ``tools/make_covering_index_fixture.py``
Contains the ``CoveringIndex`` database with one table:

``dbo.covering_base``
    1,000 rows (id INT PK, code INT, name VARCHAR(50), amount DECIMAL(10,2))
    with a covering NC index ``ix_covering`` on ``(code) INCLUDE (name, amount)``.

The NC index's leaf pages contain the key (code), included columns (name,
amount), and the clustered-key locator (id).  Their record format differs from
the base-table clustered index records.

Critical regression path
------------------------
1. If mssqlbak reads the NC index as a table (wrong extraction target) it returns
   rows with only the NC key and included columns — missing non-included columns.
2. If the NC index leaf pages confuse the base-table row reader it may crash or
   produce wrong column counts.
3. If mssqlbak double-counts (base table + NC index) it returns 2,000 rows.

Running
-------
    pytest tests/test_covering_index_coverage.py -v
    pytest -k "covering_index" -q
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows
from tools.make_covering_index_fixture import (
    DB_NAME,
    ROW_COUNT,
)

_TABLE = "covering_base"


def _read_covering_base(fixture: Path) -> list[dict[str, Any]]:
    store = PageStore.from_bak(fixture)
    schema = recover_schema(store)
    table = next((t for t in schema.tables if t.name == _TABLE), None)
    if table is None:
        pytest.fail(f"Table {_TABLE!r} not found in fixture (DB: {DB_NAME})")
    return list(read_table_rows(store, table))


@pytest.mark.fixture
def test_covering_index_row_count(fixture_bak_covering_index: Path) -> None:
    """Base table must return exactly ROW_COUNT rows — not doubled by NC index."""
    rows = _read_covering_base(fixture_bak_covering_index)
    assert len(rows) == ROW_COUNT, (
        f"expected {ROW_COUNT} rows, got {len(rows)}; "
        f"NC index pages may be double-counted or used as extraction source"
    )


@pytest.mark.fixture
def test_covering_index_all_columns_present(fixture_bak_covering_index: Path) -> None:
    """All 4 base-table columns (id, code, name, amount) must be present in each row."""
    rows = _read_covering_base(fixture_bak_covering_index)
    assert rows, "no rows returned"
    sample = rows[0]
    for col in ("id", "code", "name", "amount"):
        assert col in sample, (
            f"column {col!r} missing from extracted rows; "
            f"NC index leaf record may be used instead of base table record"
        )


@pytest.mark.fixture
def test_covering_index_spot_check_values(fixture_bak_covering_index: Path) -> None:
    """Spot-check: id, code, name, amount values for representative rows."""
    rows = _read_covering_base(fixture_bak_covering_index)
    by_id = {r["id"]: r for r in rows}
    import decimal
    for row_id in [1, 100, 500, 1_000]:
        assert row_id in by_id, f"id={row_id} missing"
        r = by_id[row_id]
        assert r["code"] == (row_id % 100), (
            f"id={row_id}: expected code={(row_id % 100)}, got {r['code']!r}"
        )
        expected_name = f"item_{row_id}"
        assert r["name"] == expected_name, (
            f"id={row_id}: expected name={expected_name!r}, got {r['name']!r}"
        )
        expected_amount = decimal.Decimal(str(round(row_id * 1.25, 2))).quantize(
            decimal.Decimal("0.01")
        )
        actual_amount = r["amount"]
        if isinstance(actual_amount, decimal.Decimal):
            actual_amount = actual_amount.quantize(decimal.Decimal("0.01"))
        assert actual_amount == expected_amount, (
            f"id={row_id}: expected amount={expected_amount}, got {actual_amount!r}"
        )


@pytest.mark.fixture
def test_covering_index_no_duplicates(fixture_bak_covering_index: Path) -> None:
    """No duplicate ids — NC index should not cause double-counting."""
    rows = _read_covering_base(fixture_bak_covering_index)
    ids = [r["id"] for r in rows]
    duplicates = sorted({i for i in ids if ids.count(i) > 1})
    assert not duplicates, (
        f"Duplicate ids (first 10): {duplicates[:10]!r}; NC index double-read?"
    )
