"""Surrogate-pairs coverage tests (Gap G-2).

Validates that mssqlbak correctly decodes UTF-16 surrogate pairs stored in
``nvarchar`` columns — supplementary code points (emoji, rare CJK) that
occupy 4 bytes (two surrogate code units) per character.

Fixture
-------
``surrogate_pairs_full.bak`` — generated by ``tools/make_surrogate_pairs_fixture.py``
Contains the ``SurrogatePairs`` database with one table:

``dbo.sc_tbl``
    id 1 — U+20000 𠀀 (rare CJK Unified Ideograph extension B, 4-byte UTF-16)
    id 2 — U+1F600 😀 (grinning face emoji, 4-byte UTF-16)
    id 3 — 🇬🇧 (GB flag: two surrogate pairs = 8 bytes total)
    id 4 — 'normal ascii string' (control: no surrogates)
    id 5 — NULL

Critical regression path
------------------------
A UTF-16 decoder that treats every 2-byte unit as a complete code point splits
surrogate pairs into two broken code units, producing garbled strings.
Python's ``bytes.decode('utf-16-le')`` handles surrogates correctly on CPython
(surrogate characters are decoded as lone surrogates, which Python tolerates
via ``surrogatepass`` or UCS-4 surrogate pairs).

Running
-------
    pytest tests/test_surrogate_pairs_coverage.py -v
    pytest -k "surrogate_pairs" -q
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows
from tools.make_surrogate_pairs_fixture import (
    DB_NAME,
    EXPECTED_VALUES,
    ROW_COUNT,
)

_TABLE = "sc_tbl"


def _read_sc_tbl(fixture: Path) -> list[dict[str, Any]]:
    store = PageStore.from_bak(fixture)
    schema = recover_schema(store)
    table = next((t for t in schema.tables if t.name == _TABLE), None)
    if table is None:
        pytest.fail(f"Table {_TABLE!r} not found in fixture (DB: {DB_NAME})")
    return list(read_table_rows(store, table))


@pytest.mark.fixture
def test_surrogate_pairs_row_count(fixture_bak_surrogate_pairs: Path) -> None:
    """All 5 rows (4 non-null + 1 null) must be returned."""
    rows = _read_sc_tbl(fixture_bak_surrogate_pairs)
    assert len(rows) == ROW_COUNT, (
        f"expected {ROW_COUNT} rows, got {len(rows)}"
    )


@pytest.mark.fixture
def test_surrogate_pairs_null_row(fixture_bak_surrogate_pairs: Path) -> None:
    """id=5 must have s IS NULL."""
    rows = _read_sc_tbl(fixture_bak_surrogate_pairs)
    by_id = {r["id"]: r for r in rows}
    assert 5 in by_id, "id=5 missing"
    assert by_id[5]["s"] is None, f"id=5: expected None, got {by_id[5]['s']!r}"


@pytest.mark.fixture
def test_surrogate_pairs_ascii_control(fixture_bak_surrogate_pairs: Path) -> None:
    """id=4 must decode as plain ASCII without corruption."""
    rows = _read_sc_tbl(fixture_bak_surrogate_pairs)
    by_id = {r["id"]: r for r in rows}
    assert 4 in by_id, "id=4 (ASCII control row) missing"
    assert by_id[4]["s"] == EXPECTED_VALUES[4], (
        f"id=4: expected {EXPECTED_VALUES[4]!r}, got {by_id[4]['s']!r}"
    )


@pytest.mark.fixture
def test_surrogate_pairs_cjk_extension_b(fixture_bak_surrogate_pairs: Path) -> None:
    """id=1 (U+20000 𠀀) — rare CJK surrogate pair must decode correctly."""
    rows = _read_sc_tbl(fixture_bak_surrogate_pairs)
    by_id = {r["id"]: r for r in rows}
    assert 1 in by_id, "id=1 missing"
    expected = EXPECTED_VALUES[1]
    actual = by_id[1]["s"]
    assert actual == expected, (
        f"id=1: expected U+20000 ({expected!r}), got {actual!r}; "
        f"surrogate pair may have been split or decoded incorrectly"
    )


@pytest.mark.fixture
def test_surrogate_pairs_emoji(fixture_bak_surrogate_pairs: Path) -> None:
    """id=2 (😀 U+1F600) — emoji surrogate pair must decode correctly."""
    rows = _read_sc_tbl(fixture_bak_surrogate_pairs)
    by_id = {r["id"]: r for r in rows}
    assert 2 in by_id, "id=2 missing"
    expected = EXPECTED_VALUES[2]
    actual = by_id[2]["s"]
    assert actual == expected, (
        f"id=2: expected 😀 ({expected!r}), got {actual!r}; "
        f"emoji surrogate pair may have been split or decoded incorrectly"
    )


@pytest.mark.fixture
def test_surrogate_pairs_flag_emoji(fixture_bak_surrogate_pairs: Path) -> None:
    """id=3 (🇬🇧 GB flag — two surrogate pairs = 8 UTF-16 bytes) must decode correctly."""
    rows = _read_sc_tbl(fixture_bak_surrogate_pairs)
    by_id = {r["id"]: r for r in rows}
    assert 3 in by_id, "id=3 missing"
    expected = EXPECTED_VALUES[3]
    actual = by_id[3]["s"]
    assert actual == expected, (
        f"id=3: expected 🇬🇧 ({expected!r}), got {actual!r}; "
        f"double surrogate pair (flag emoji) may be decoded incorrectly"
    )
