"""CCI PARTITION SWITCH coverage tests (Gap C-9).

Validates that mssqlbak correctly reads CCI rowgroups after a metadata-only
``ALTER TABLE src SWITCH TO dst`` operation reassigns rowgroup ownership.

Fixture
-------
``cci_switch_full.bak`` — generated by ``tools/make_cci_switch_fixture.py``
Contains the ``CciSwitch`` database with two CCI tables:

``dbo.cci_switch_src``
    Empty after SWITCH (0 rows).  The 1,200 rows that were here before the
    switch were reassigned to ``cci_switch_dst`` by the metadata-only operation.

``dbo.cci_switch_dst``
    Holds 1,200 rows (id 1–1,200, batch=1, val=id*10) after SWITCH.
    Physical pages were not moved; only the catalog mapping changed.

Critical regression path
------------------------
If mssqlbak uses a stale or physical-only scan rather than the catalog's
object_id→rowset_id mapping:
  - It might return 1,200 rows under the *source* table (wrong table).
  - It might return 0 rows under the *destination* table (missed mapping).
  - It might double-count if it reads both tables' allocation units.

Running
-------
    pytest tests/test_cci_switch_coverage.py -v
    pytest -k "cci_switch" -q
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows
from tools.make_cci_switch_fixture import (
    DB_NAME,
    DST_TABLE,
    SWITCHED_ROWS,
    SRC_TABLE,
)


def _read_table(fixture: Path, table_name: str) -> list[dict[str, Any]]:
    store = PageStore.from_bak(fixture)
    schema = recover_schema(store)
    table = next((t for t in schema.tables if t.name == table_name), None)
    if table is None:
        pytest.fail(f"Table {table_name!r} not found in fixture (DB: {DB_NAME})")
    return list(read_table_rows(store, table))


@pytest.mark.fixture
def test_cci_switch_src_is_empty(fixture_bak_cci_switch: Path) -> None:
    """Source table must have 0 rows after the PARTITION SWITCH."""
    rows = _read_table(fixture_bak_cci_switch, SRC_TABLE)
    assert len(rows) == 0, (
        f"expected 0 rows in {SRC_TABLE!r} (post-switch), got {len(rows)}; "
        f"rowgroup ownership may not be following the catalog switch"
    )


@pytest.mark.fixture
def test_cci_switch_dst_row_count(fixture_bak_cci_switch: Path) -> None:
    """Destination table must have exactly SWITCHED_ROWS rows after the SWITCH."""
    rows = _read_table(fixture_bak_cci_switch, DST_TABLE)
    assert len(rows) == SWITCHED_ROWS, (
        f"expected {SWITCHED_ROWS} rows in {DST_TABLE!r} (post-switch), "
        f"got {len(rows)}; "
        f"rowgroup catalog mapping may be stale after PARTITION SWITCH"
    )


@pytest.mark.fixture
def test_cci_switch_dst_no_duplicates(fixture_bak_cci_switch: Path) -> None:
    """No duplicate ids in the destination table."""
    rows = _read_table(fixture_bak_cci_switch, DST_TABLE)
    ids = [r["id"] for r in rows]
    duplicates = sorted({i for i in ids if ids.count(i) > 1})
    assert not duplicates, (
        f"Duplicate ids in {DST_TABLE!r}: {duplicates[:10]!r}"
    )


@pytest.mark.fixture
def test_cci_switch_dst_spot_check(fixture_bak_cci_switch: Path) -> None:
    """Spot-check: val = id * 10 for first, mid, last rows in destination."""
    rows = _read_table(fixture_bak_cci_switch, DST_TABLE)
    by_id = {r["id"]: r for r in rows}
    checks = [
        (1,            10),
        (SWITCHED_ROWS // 2, (SWITCHED_ROWS // 2) * 10),
        (SWITCHED_ROWS, SWITCHED_ROWS * 10),
    ]
    for check_id, expected_val in checks:
        assert check_id in by_id, f"{DST_TABLE!r} id={check_id} missing"
        actual = by_id[check_id]["val"]
        assert actual == expected_val, (
            f"{DST_TABLE!r} id={check_id}: expected val={expected_val}, got {actual!r}"
        )
