"""Max-row-width coverage tests (Gap H-3).

Validates that mssqlbak correctly decodes pages with a single slot (one row
per page), which occurs when rows are near the 8,060-byte in-row limit.

Fixture
-------
``max_row_width_full.bak`` — generated by ``tools/make_max_row_width_fixture.py``
Contains the ``MaxRowWidth`` database with one table:

``dbo.wide_row``
    5 rows, each CHAR(8,000) — approximately 8,004 bytes per row.
    id 1 → data = 'AAAA...A' (8,000 A's)
    id 2 → data = 'BBBB...B' (8,000 B's)
    id 3 → data = 'CCCC...C' (8,000 C's)
    id 4 → data = 'DDDD...D' (8,000 D's)
    id 5 → data = 'EEEE...E' (8,000 E's)

Critical regression path
------------------------
Slot-array parsers that assume ≥ 2 rows per page, or that use an incorrect
slot-count field, will crash or return wrong row counts on single-slot pages.

Running
-------
    pytest tests/test_max_row_width_coverage.py -v
    pytest -k "max_row_width" -q
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows
from tools.make_max_row_width_fixture import (
    DATA_LEN,
    DB_NAME,
    ROW_COUNT,
    _FILL_CHARS,
)

_TABLE = "wide_row"


def _read_wide_rows(fixture: Path) -> list[dict[str, Any]]:
    store = PageStore.from_bak(fixture)
    schema = recover_schema(store)
    table = next((t for t in schema.tables if t.name == _TABLE), None)
    if table is None:
        pytest.fail(f"Table {_TABLE!r} not found in fixture (DB: {DB_NAME})")
    return list(read_table_rows(store, table))


@pytest.mark.fixture
def test_max_row_width_row_count(fixture_bak_max_row_width: Path) -> None:
    """All 5 wide rows must be returned (one row per page)."""
    rows = _read_wide_rows(fixture_bak_max_row_width)
    assert len(rows) == ROW_COUNT, (
        f"expected {ROW_COUNT} rows, got {len(rows)}; "
        f"single-slot pages may be mis-read"
    )


@pytest.mark.fixture
def test_max_row_width_data_length(fixture_bak_max_row_width: Path) -> None:
    """Each data value must be exactly DATA_LEN characters long."""
    rows = _read_wide_rows(fixture_bak_max_row_width)
    by_id = {r["id"]: r for r in rows}
    for row_id in range(1, ROW_COUNT + 1):
        assert row_id in by_id, f"row id={row_id} missing"
        data = by_id[row_id]["data"]
        assert data is not None, f"row id={row_id}: data is NULL"
        assert len(data) == DATA_LEN, (
            f"row id={row_id}: expected data length {DATA_LEN}, got {len(data)}"
        )


@pytest.mark.fixture
def test_max_row_width_data_content(fixture_bak_max_row_width: Path) -> None:
    """Each row's data must consist of the expected fill character."""
    rows = _read_wide_rows(fixture_bak_max_row_width)
    by_id = {r["id"]: r for r in rows}
    for row_id in range(1, ROW_COUNT + 1):
        fill = _FILL_CHARS[(row_id - 1) % len(_FILL_CHARS)]
        data = by_id[row_id]["data"]
        # CHAR is space-padded to exactly DATA_LEN chars; all chars should be `fill`
        # (SQL Server right-pads CHAR columns to their declared length with spaces,
        # but since DATA_LEN matches CHAR(DATA_LEN), REPLICATE fills the full width).
        stripped = data.rstrip()
        expected = fill * DATA_LEN
        assert stripped == expected.rstrip(), (
            f"row id={row_id}: expected all '{fill}' × {DATA_LEN}, "
            f"got first chars {data[:20]!r}"
        )


@pytest.mark.fixture
def test_max_row_width_all_ids_present(fixture_bak_max_row_width: Path) -> None:
    """All 5 row IDs (1–5) must be present with no duplicates."""
    rows = _read_wide_rows(fixture_bak_max_row_width)
    ids = sorted(r["id"] for r in rows)
    assert ids == list(range(1, ROW_COUNT + 1)), (
        f"expected ids 1–{ROW_COUNT}, got {ids}"
    )
