"""Gap C-8 — CCI string/binary min-max segment metadata (SS2022+).

SS2022 added per-segment min/max metadata for string and binary CCI columns.
Rows where every string value is NULL produce a NULL min/max entry — the
decoder must handle both present and absent min/max without corruption.

Fixture: ``cci_string_minmax_full.bak``
Generated by: ``python -m tools.fixture_run all-versions --suite cci-string-minmax --version 2022``
"""
from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows


def test_cci_string_minmax_row_count(fixture_bak_cci_string_minmax: str) -> None:
    from tools.make_cci_string_minmax_fixture import ROW_COUNT, TABLE

    store = PageStore.from_bak(fixture_bak_cci_string_minmax)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None, f"table {TABLE!r} not found"
    rows = list(read_table_rows(store, tbl))
    assert len(rows) == ROW_COUNT


def test_cci_string_minmax_null_rows(fixture_bak_cci_string_minmax: str) -> None:
    """Rows whose id is divisible by NULL_STRIDE have NULL name and label."""
    from tools.make_cci_string_minmax_fixture import NULL_STRIDE, ROW_COUNT, TABLE

    store = PageStore.from_bak(fixture_bak_cci_string_minmax)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None

    rows_by_id = {r["id"]: r for r in read_table_rows(store, tbl)}
    assert len(rows_by_id) == ROW_COUNT

    null_ids = [i for i in range(1, ROW_COUNT + 1) if i % NULL_STRIDE == 0]
    assert null_ids, "no NULL rows expected — check NULL_STRIDE constant"

    for nid in null_ids:
        row = rows_by_id[nid]
        assert row["name"] is None, f"id={nid}: expected NULL name, got {row['name']!r}"
        assert row["label"] is None, f"id={nid}: expected NULL label, got {row['label']!r}"


def test_cci_string_minmax_nonnull_rows(fixture_bak_cci_string_minmax: str) -> None:
    """Non-NULL rows have correct name, label, and score values."""
    from tools.make_cci_string_minmax_fixture import NULL_STRIDE, TABLE

    store = PageStore.from_bak(fixture_bak_cci_string_minmax)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None

    rows_by_id = {r["id"]: r for r in read_table_rows(store, tbl)}

    for sample_id in [1, 7, 21, 99, 101]:
        if sample_id % NULL_STRIDE == 0:
            continue
        row = rows_by_id.get(sample_id)
        if row is None:
            continue
        assert row["name"] == f"name_{sample_id}", f"id={sample_id}: {row['name']!r}"
        assert row["label"] == f"lbl_{sample_id}", f"id={sample_id}: {row['label']!r}"
        assert row["score"] == sample_id * 3, f"id={sample_id}: {row['score']!r}"
