"""CCI multiple-rowgroup coverage tests (Gap C-3).

Validates that mssqlbak reads ALL compressed rowgroups in a CCI table, not
just the first one.

Fixture
-------
``multi_rowgroup_full.bak`` — generated by ``tools/make_multi_rowgroup_fixture.py``
Contains the ``MultiRowgroup`` database with one table:

``cs_multi``
    Batch 1: 1,200 rows (id   1– 1,200, batch=1) → compressed rowgroup 0
    Batch 2:   600 rows (id 1,201– 1,800, batch=2) → compressed rowgroup 1
    Batch 3:   300 rows (id 1,801– 2,100, batch=3) → compressed rowgroup 2
    Total: 2,100 rows in 3 separate compressed rowgroups.

    val = id * 10 for all rows.

Critical regression path
------------------------
If mssqlbak stops iterating after the first rowgroup it returns only 1,200 rows
(batch 1) and silently drops batches 2 and 3.  The row-count and per-batch
presence tests catch this regression.

Running
-------
    pytest tests/test_multi_rowgroup_coverage.py -v
    pytest -k "multi_rowgroup" -q
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows
from tools.make_multi_rowgroup_fixture import (
    BATCH1_ROWS,
    BATCH2_ROWS,
    BATCH3_ROWS,
    DB_NAME,
    TOTAL_ROWS,
)

_TABLE = "cs_multi"


def _read_cs_multi(fixture: Path) -> list[dict[str, Any]]:
    store = PageStore.from_bak(fixture)
    schema = recover_schema(store)
    table = next((t for t in schema.tables if t.name == _TABLE), None)
    if table is None:
        pytest.fail(f"Table {_TABLE!r} not found in fixture (DB: {DB_NAME})")
    return list(read_table_rows(store, table))


@pytest.mark.fixture
def test_multi_rowgroup_total_count(fixture_bak_multi_rowgroup: Path) -> None:
    """cs_multi must return all 2,100 rows from 3 compressed rowgroups."""
    rows = _read_cs_multi(fixture_bak_multi_rowgroup)
    assert len(rows) == TOTAL_ROWS, (
        f"expected {TOTAL_ROWS} total rows, got {len(rows)}; "
        f"mssqlbak may be stopping after the first compressed rowgroup"
    )


@pytest.mark.fixture
def test_multi_rowgroup_batch1_present(fixture_bak_multi_rowgroup: Path) -> None:
    """All 1,200 batch-1 rows (batch=1, id 1–1,200) must be present."""
    rows = _read_cs_multi(fixture_bak_multi_rowgroup)
    b1 = [r for r in rows if r.get("batch") == 1]
    assert len(b1) == BATCH1_ROWS, (
        f"expected {BATCH1_ROWS} batch-1 rows, got {len(b1)}"
    )


@pytest.mark.fixture
def test_multi_rowgroup_batch2_present(fixture_bak_multi_rowgroup: Path) -> None:
    """All 600 batch-2 rows (batch=2, id 1,201–1,800) must be present.

    This is the core C-3 assertion: a decoder that stops after rowgroup 0
    will return 0 batch-2 rows.
    """
    rows = _read_cs_multi(fixture_bak_multi_rowgroup)
    b2 = [r for r in rows if r.get("batch") == 2]
    assert len(b2) == BATCH2_ROWS, (
        f"expected {BATCH2_ROWS} batch-2 rows, got {len(b2)}; "
        f"rowgroup 1 may not be read"
    )


@pytest.mark.fixture
def test_multi_rowgroup_batch3_present(fixture_bak_multi_rowgroup: Path) -> None:
    """All 300 batch-3 rows (batch=3, id 1,801–2,100) must be present.

    This catches a decoder that reads only the first two rowgroups.
    """
    rows = _read_cs_multi(fixture_bak_multi_rowgroup)
    b3 = [r for r in rows if r.get("batch") == 3]
    assert len(b3) == BATCH3_ROWS, (
        f"expected {BATCH3_ROWS} batch-3 rows, got {len(b3)}; "
        f"rowgroup 2 may not be read"
    )


@pytest.mark.fixture
def test_multi_rowgroup_no_duplicates(fixture_bak_multi_rowgroup: Path) -> None:
    """Each id must appear exactly once across all rowgroups."""
    rows = _read_cs_multi(fixture_bak_multi_rowgroup)
    ids = [r["id"] for r in rows]
    duplicates = sorted({i for i in ids if ids.count(i) > 1})
    assert not duplicates, (
        f"Duplicate ids: {duplicates[:10]!r} — rowgroups double-read?"
    )


@pytest.mark.fixture
def test_multi_rowgroup_spot_check_values(fixture_bak_multi_rowgroup: Path) -> None:
    """Spot-check: val = id * 10 for representative rows from each batch."""
    rows = _read_cs_multi(fixture_bak_multi_rowgroup)
    by_id = {r["id"]: r for r in rows}
    checks = [
        (1,     10),      # batch 1 first row
        (600,   6_000),   # batch 1 mid
        (1_200, 12_000),  # batch 1 last
        (1_201, 12_010),  # batch 2 first
        (1_500, 15_000),  # batch 2 mid
        (1_800, 18_000),  # batch 2 last
        (1_801, 18_010),  # batch 3 first
        (2_100, 21_000),  # batch 3 last
    ]
    for check_id, expected_val in checks:
        assert check_id in by_id, f"id={check_id} missing"
        actual = by_id[check_id]["val"]
        assert actual == expected_val, (
            f"id={check_id}: expected val={expected_val}, got {actual!r}"
        )
