"""Gap A-5 — Non-default BLOCKSIZE backup.

mssqlbak._detect_block_size() probes every power-of-two from 512 to 65536.
A backup taken with ``BLOCKSIZE = 4096`` must be auto-detected and produce
the correct row count and values.

Fixture: ``backup_blocksize_full.bak``
Generated by: ``python -m tools.fixture_run all-versions --suite backup-blocksize``
"""
import pytest

from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows


# ---------------------------------------------------------------------------
# Parametrised over all fixture versions
# ---------------------------------------------------------------------------

def test_blocksize_row_count(fixture_bak_backup_blocksize: str) -> None:
    from tools.make_backup_blocksize_fixture import ROW_COUNT, TABLE

    store = PageStore.from_bak(fixture_bak_backup_blocksize)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None, f"table {TABLE!r} not found in schema"
    rows = list(read_table_rows(store, tbl))
    assert len(rows) == ROW_COUNT, f"expected {ROW_COUNT} rows, got {len(rows)}"


def test_blocksize_values(fixture_bak_backup_blocksize: str) -> None:
    from tools.make_backup_blocksize_fixture import ROW_COUNT, TABLE

    store = PageStore.from_bak(fixture_bak_backup_blocksize)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None

    rows = {r["id"]: r for r in read_table_rows(store, tbl)}
    assert len(rows) == ROW_COUNT

    # Spot-check the deterministic formula: val='row_N', n=N*7
    for sample_id in [1, 10, 50, 99, 100]:
        row = rows.get(sample_id)
        assert row is not None, f"row id={sample_id} missing"
        assert row["val"] == f"row_{sample_id}", f"wrong val for id={sample_id}: {row['val']!r}"
        assert row["n"] == sample_id * 7, f"wrong n for id={sample_id}: {row['n']!r}"
