"""Regular-CCI enc=5 CHAR with a >64 KiB string pool — ARCHIVE-probe false-positive guard.

A *regular* (non-ARCHIVE) CCI ``CHAR(n)`` column whose distinct values overflow a
64 KiB segment pool emits the ``0xFFFF`` sentinel in its u16 index region.  The
``_decode_enc5`` ARCHIVE detector used to treat that sentinel (plus a following
``u16 >= 0xFFF0``) as a compressed-sub-block marker and misroute the whole column
to the ARCHIVE decoder, decoding every row as **NULL**.

This was observed in the wild on ``tpcxbb_1gb.bak`` (``dbo.customer.c_login``
CHAR(13), ``dbo.customer_address.ca_zip`` CHAR(10)).  The fix gates the probe
behind ``is_archive``; these tests fail on the pre-fix decoder (all-NULL) and pass
once the column is decoded as raw enc=5.

Fixture: ``cci_enc5_largepool_full.bak``
Generated by: ``python -m tools.fixture_run all-versions --suite cci-enc5-largepool``
"""
import hashlib
import os
from pathlib import Path

import pytest

from mssqlbak.catalog import recover_schema
from mssqlbak.columnstore import read_columnstore_batches
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows

_FIXTURE_DIR = Path(os.environ.get("FIXTURE_DIR", str(Path(__file__).parent / "fixtures_2022")))
_MATRIX_BAK = _FIXTURE_DIR / "cci_enc5_largepool_matrix_full.bak"


def _table(bak: str):
    from tools.make_cci_enc5_largepool_fixture import TABLE

    store = PageStore.from_bak(bak)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None, f"table {TABLE!r} not found"
    return store, tbl


def _named_table(bak: str | Path, table_name: str):
    store = PageStore.from_bak(str(bak))
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.schema == "dbo" and t.name == table_name), None)
    assert tbl is not None, f"table {table_name!r} not found"
    return store, tbl


def _batch_nulls(bak: str) -> tuple[int, dict[str, int]]:
    """Decode via the Arrow batches path (the one the bug bit, used by extract)."""
    store, tbl = _table(bak)
    n = 0
    nulls: dict[str, int] = {}
    for batch in read_columnstore_batches(store, tbl):
        n += batch.num_rows
        for name in batch.schema.names:
            nulls[name] = nulls.get(name, 0) + batch.column(name).null_count
    return n, nulls


def test_cci_enc5_largepool_row_count(fixture_bak_cci_enc5_largepool: str) -> None:
    from tools.make_cci_enc5_largepool_fixture import ROW_COUNT

    n, _ = _batch_nulls(fixture_bak_cci_enc5_largepool)
    assert n == ROW_COUNT


def test_cci_enc5_largepool_not_all_null(fixture_bak_cci_enc5_largepool: str) -> None:
    """The CHAR columns must NOT decode as all-NULL (the pre-fix failure mode).

    The Arrow batches path (``read_columnstore_batches``, used by
    ``extract_bak_to_delta``) is the one that regressed: the pre-fix decoder
    misrouted the >64 KiB-pool CHAR segment to the ARCHIVE decoder and returned
    ``null_count == ROW_COUNT``.  The correct null_count is the sparse-NULL count
    ``ROW_COUNT // NULL_STRIDE``.
    """
    from tools.make_cci_enc5_largepool_fixture import NULL_STRIDE, ROW_COUNT

    _, nulls = _batch_nulls(fixture_bak_cci_enc5_largepool)
    expected_nulls = ROW_COUNT // NULL_STRIDE

    for col in ("login", "code"):
        assert nulls.get(col, 0) == expected_nulls, (
            f"{col}: expected {expected_nulls} NULLs, got {nulls.get(col)} "
            f"(all-NULL == {ROW_COUNT} means the enc=5 ARCHIVE false-positive regressed)"
        )


def test_cci_enc5_largepool_values_and_positions(fixture_bak_cci_enc5_largepool: str) -> None:
    """Per-row values + NULL positions should match the deterministic MD5-hex source.

    SQL Server ``CONVERT(..., 2)`` emits uppercase hex.
    """
    from tools.make_cci_enc5_largepool_fixture import NULL_STRIDE

    def expect_login(idv: int) -> str:
        return hashlib.md5(str(idv).encode()).hexdigest().upper()[:13]

    def expect_code(idv: int) -> str:
        return hashlib.md5(str(idv + 1000002).encode()).hexdigest().upper()[:10]

    store, tbl = _table(fixture_bak_cci_enc5_largepool)
    for row in read_table_rows(store, tbl):
        idv = row["id"]
        if idv % NULL_STRIDE == 0:
            assert row["login"] is None and row["code"] is None, f"id={idv}: expected NULLs"
        else:
            assert row["login"].rstrip() == expect_login(idv), f"id={idv}: login={row['login']!r}"
            assert row["code"].rstrip() == expect_code(idv), f"id={idv}: code={row['code']!r}"


@pytest.mark.skipif(not _MATRIX_BAK.exists(), reason="cci_enc5_largepool_matrix fixture not present")
def test_cci_enc5_largepool_matrix_secondary_region_values() -> None:
    """Format D large-pool secondary regions should contribute real values to the multiset."""

    sample_ids = {25_001, 50_001, 79_999}

    def expect_val(idv: int) -> str | None:
        md5_hex = hashlib.md5(str(idv).encode()).hexdigest().upper()
        return md5_hex[: 1 + ((idv - 1) % 13)]

    store, tbl = _named_table(_MATRIX_BAK, "char_80000_distinct_var")
    observed_values: set[str] = set()
    for row in read_table_rows(store, tbl):
        if row["val"] is not None:
            observed_values.add(row["val"].rstrip())

    for idv in sorted(sample_ids):
        expected = expect_val(idv)
        assert expected in observed_values, f"id={idv}: expected value {expected!r} absent"


@pytest.mark.skipif(not _MATRIX_BAK.exists(), reason="cci_enc5_largepool_matrix fixture not present")
@pytest.mark.parametrize(
    ("table_name", "sample_ids", "cardinality"),
    [
        ("char_32767_distinct_var", {1, 999, 1001, 25_001}, None),
        ("char_32768_distinct_var", {1, 999, 1001, 25_001}, None),
        ("char_80000_lowcard_var", {25_001, 50_001, 79_999}, 4096),
        ("varchar_80000_distinct_var", {25_001, 50_001, 79_999}, None),
    ],
)
def test_cci_enc5_largepool_matrix_remaining_variants_values(
    table_name: str,
    sample_ids: set[int],
    cardinality: int | None,
) -> None:
    """Remaining matrix variants should decode real variable-width values."""

    def expect_val(idv: int) -> str | None:
        if idv % 1000 == 0:
            return None
        seed = ((idv - 1) % cardinality) + 1 if cardinality is not None else idv
        md5_hex = hashlib.md5(str(seed).encode()).hexdigest().upper()
        return md5_hex[: 1 + ((idv - 1) % 13)]

    store, tbl = _named_table(_MATRIX_BAK, table_name)
    observed_values: set[str] = set()
    for row in read_table_rows(store, tbl):
        if row["val"] is not None:
            observed_values.add(row["val"].rstrip())

    assert "\x00" * 13 not in observed_values
    assert not any("\x00" in value for value in observed_values)

    for idv in sorted(sample_ids):
        expected = expect_val(idv)
        assert expected in observed_values, (
            f"{table_name} id={idv}: expected value {expected!r} absent"
        )
