"""Gap D-5 — VECTOR column type (SS2025 only).

The VECTOR(N) type (SS2025) stores a fixed-dimension float32 array in a binary
format: 4-byte header (type=0x53, dimensions uint16-LE, element_type=0x03)
followed by the packed float32 array.  mssqlbak must extract these without
crashing and return the correct float values (or raw bytes).

Fixture: ``vector_full.bak`` (SS2025 fixture directory only)
Generated by: ``python -m tools.fixture_run all-versions --suite vector --version 2025``
"""
import struct

import pytest

from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows


def _decode_vector(raw: object) -> list[float] | None:
    """Decode a VECTOR value returned by mssqlbak.

    mssqlbak surfaces VECTOR columns as raw bytes (VARBINARY on-disk).
    The SS2025 binary VECTOR format is an 8-byte header followed by packed
    float32 values:

      Bytes 0-1: format identifier LE uint16 (0x01A9 for float32 vectors)
      Bytes 2-3: number of dimensions LE uint16
      Bytes 4-7: reserved/flags LE uint32 (always 0)
      Bytes 8+:  float32 array, one element per dimension, LE byte order

    Returns a list of floats, or None if the value cannot be decoded.
    """
    if raw is None:
        return None
    if isinstance(raw, list):
        return [float(x) for x in raw]
    if isinstance(raw, str):
        stripped = raw.strip().lstrip("[").rstrip("]")
        return [float(x.strip()) for x in stripped.split(",")]
    if isinstance(raw, (bytes, bytearray)):
        # Need at least the 8-byte header
        if len(raw) < 8:
            return None
        n_dims = struct.unpack_from("<H", raw, 2)[0]
        floats_start = 8
        floats_end = floats_start + n_dims * 4
        if len(raw) < floats_end:
            return None
        return list(struct.unpack_from(f"<{n_dims}f", raw, floats_start))
    return None


def test_vector_row_count(fixture_bak_vector: str) -> None:
    from tools.make_vector_fixture import ROW_COUNT, TABLE

    store = PageStore.from_bak(fixture_bak_vector)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None, f"table {TABLE!r} not found"
    rows = list(read_table_rows(store, tbl))
    assert len(rows) == ROW_COUNT


def test_vector_values_no_crash(fixture_bak_vector: str) -> None:
    """All VECTOR column values must be decodable (not None, not garbage)."""
    from tools.make_vector_fixture import TABLE

    store = PageStore.from_bak(fixture_bak_vector)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None

    for row in read_table_rows(store, tbl):
        raw = row.get("v")
        floats = _decode_vector(raw)
        assert floats is not None, f"id={row['id']}: cannot decode VECTOR value {raw!r}"
        assert len(floats) == 3, f"id={row['id']}: expected 3 floats, got {len(floats)}"


def test_vector_known_values(fixture_bak_vector: str) -> None:
    """Spot-check known float values for the first 5 rows."""
    from tools.make_vector_fixture import KNOWN_VECTORS, TABLE

    store = PageStore.from_bak(fixture_bak_vector)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None

    rows_by_id = {r["id"]: r for r in read_table_rows(store, tbl)}

    for row_id, expected_floats in KNOWN_VECTORS[:5]:
        row = rows_by_id.get(row_id)
        assert row is not None, f"row id={row_id} missing"
        actual = _decode_vector(row["v"])
        assert actual is not None, f"id={row_id}: cannot decode {row['v']!r}"
        assert len(actual) == len(expected_floats)
        for i, (a, e) in enumerate(zip(actual, expected_floats)):
            assert abs(a - e) < abs(e) * 1e-5 + 1e-6, (
                f"id={row_id}[{i}]: expected {e}, got {a}"
            )
