"""High slot density coverage tests (Gap H-4).

Validates that mssqlbak correctly iterates pages with many rows per page
(high slot density), where the slot array at the end of each page is large.

Fixture
-------
``high_slot_density_full.bak`` — generated by ``tools/make_high_slot_density_fixture.py``
Contains the ``HighSlotDensity`` database with one table:

``dbo.tiny_row``
    100,000 rows, each containing a single TINYINT column ``a``.
    a = pk % 256  (values cycle 0–255 across all rows).
    TINYINT rows are tiny (~14 bytes on page) → ~500 rows per 8 KB page.
    The slot array grows accordingly (~4 bytes × 500 slots per page = ~2 KB).

Critical regression path
------------------------
Slot-array iteration bugs (wrong slot_count field, off-by-one, reading past the
last slot) surface when hundreds of slots are present per page.  A row-count
error here means every heap with small rows is silently broken.

Running
-------
    pytest tests/test_high_slot_density_coverage.py -v
    pytest -k "high_slot_density" -q
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows
from tools.make_high_slot_density_fixture import (
    DB_NAME,
    ROW_COUNT,
)

_TABLE = "tiny_row"


def _read_tiny_rows(fixture: Path) -> list[dict[str, Any]]:
    store = PageStore.from_bak(fixture)
    schema = recover_schema(store)
    table = next((t for t in schema.tables if t.name == _TABLE), None)
    if table is None:
        pytest.fail(f"Table {_TABLE!r} not found in fixture (DB: {DB_NAME})")
    return list(read_table_rows(store, table))


@pytest.mark.fixture
def test_high_slot_density_row_count(fixture_bak_high_slot_density: Path) -> None:
    """All 100,000 tiny rows must be returned — no slot-iteration truncation."""
    rows = _read_tiny_rows(fixture_bak_high_slot_density)
    assert len(rows) == ROW_COUNT, (
        f"expected {ROW_COUNT:,} rows, got {len(rows):,}; "
        f"slot-array iteration may be truncated for high-density pages"
    )


@pytest.mark.fixture
def test_high_slot_density_value_distribution(fixture_bak_high_slot_density: Path) -> None:
    """Values cycle 0–255; each value should appear ~391 times (100,000 / 256)."""
    rows = _read_tiny_rows(fixture_bak_high_slot_density)
    counts: dict[int, int] = {}
    for r in rows:
        v = r["a"]
        counts[v] = counts.get(v, 0) + 1
    # All 256 values (0–255) must be present
    assert len(counts) == 256, (
        f"expected 256 distinct values (0–255), got {len(counts)}; "
        f"missing: {sorted(set(range(256)) - set(counts))[:10]!r}"
    )
    # Each value appears roughly ROW_COUNT / 256 = 390.625 times
    expected_per_val = ROW_COUNT // 256   # 390
    for v, cnt in counts.items():
        ok = cnt in (expected_per_val, expected_per_val + 1)
        assert ok, (
            f"value {v}: expected ~{expected_per_val} occurrences, got {cnt}"
        )


@pytest.mark.fixture
def test_high_slot_density_no_null_values(fixture_bak_high_slot_density: Path) -> None:
    """Column ``a`` is NOT NULL — no row should return None."""
    rows = _read_tiny_rows(fixture_bak_high_slot_density)
    nulls = [r for r in rows if r.get("a") is None]
    assert not nulls, f"{len(nulls)} rows have a=None; TINYINT NOT NULL column"
