"""CCI open-delta-store coverage tests (Gap C-1).

Validates that ``_read_columnstore_delta_rows`` in ``mssqlbak/columnstore.py``
correctly finds and returns rows that are in the open (uncompressed) delta store
at backup time — i.e. rows that were inserted into a CCI after the last
``REORGANIZE WITH (COMPRESS_ALL_ROW_GROUPS = ON)`` call (or never reorganized).

Fixture
-------
``delta_rowgroup_full.bak`` — generated by ``tools/make_delta_rowgroup_fixture.py``
Contains the ``DeltaRowgroup`` database with two tables:

``cs_mixed``
    100 rows with category='compressed' (id 1–100) are in a compressed segment.
    50 rows with category='delta' (id 101–150) are in the open delta store.
    Total: 150 rows.

``cs_delta_only``
    30 rows (id 1–30) with no compressed segment at all — all rows are in the
    open delta store.

Critical regression path
------------------------
Without this fixture, ``_read_columnstore_delta_rows`` has no integration coverage.
Any regression that silently skips the delta-store B-tree scan would cause row loss
with no existing test to catch it.

Running
-------
    pytest tests/test_delta_rowgroup_coverage.py -v
    pytest -k "delta_rowgroup" -q
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows
from tools.make_delta_rowgroup_fixture import (
    CS_DELTA_ONLY_ROWS,
    CS_MIXED_COMPRESSED,
    CS_MIXED_DELTA,
    CS_MIXED_TOTAL,
    DB_NAME,
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _read_table(fixture: Path, table_name: str) -> list[dict[str, Any]]:
    """Return all rows from *table_name* in the fixture."""
    store = PageStore.from_bak(fixture)
    schema = recover_schema(store)
    table = next((t for t in schema.tables if t.name == table_name), None)
    if table is None:
        pytest.fail(f"Table {table_name!r} not found in fixture (DB: {DB_NAME})")
    return list(read_table_rows(store, table))


# ---------------------------------------------------------------------------
# cs_mixed: compressed segment rows + open delta rows
# ---------------------------------------------------------------------------

@pytest.mark.fixture
def test_cs_mixed_total_row_count(fixture_bak_delta_rowgroup: Path) -> None:
    """cs_mixed must return all 150 rows — 100 from segment + 50 from delta store."""
    rows = _read_table(fixture_bak_delta_rowgroup, "cs_mixed")
    assert len(rows) == CS_MIXED_TOTAL, (
        f"expected {CS_MIXED_TOTAL} rows in cs_mixed, got {len(rows)}; "
        f"delta-store rows may have been silently dropped"
    )


@pytest.mark.fixture
def test_cs_mixed_compressed_rows_present(fixture_bak_delta_rowgroup: Path) -> None:
    """All 100 compressed-segment rows must be present in cs_mixed (id 1–100).

    kind=1 marks rows that were compressed before backup via REORGANIZE.
    Using INT avoids any VARCHAR-in-CCI-segment encoding issues.
    """
    rows = _read_table(fixture_bak_delta_rowgroup, "cs_mixed")
    compressed = [r for r in rows if r.get("kind") == 1]
    assert len(compressed) == CS_MIXED_COMPRESSED, (
        f"expected {CS_MIXED_COMPRESSED} compressed rows (kind=1), got {len(compressed)}"
    )


@pytest.mark.fixture
def test_cs_mixed_delta_rows_present(fixture_bak_delta_rowgroup: Path) -> None:
    """All 50 open-delta-store rows must be present in cs_mixed (id 101–150).

    This is the core C-1 assertion: rows inserted after the last REORGANIZE
    (kind=2) must be read via _read_columnstore_delta_rows and included in the output.
    """
    rows = _read_table(fixture_bak_delta_rowgroup, "cs_mixed")
    delta = [r for r in rows if r.get("kind") == 2]
    assert len(delta) == CS_MIXED_DELTA, (
        f"expected {CS_MIXED_DELTA} open-delta-store rows (kind=2), got {len(delta)}; "
        f"_read_columnstore_delta_rows may not be finding the open rowgroup"
    )


@pytest.mark.fixture
def test_cs_mixed_no_duplicate_rows(fixture_bak_delta_rowgroup: Path) -> None:
    """No row id should appear twice — tombstoned delta stores must not be double-read."""
    rows = _read_table(fixture_bak_delta_rowgroup, "cs_mixed")
    ids = [r["id"] for r in rows]
    duplicates = sorted({i for i in ids if ids.count(i) > 1})
    assert not duplicates, (
        f"Duplicate ids in cs_mixed: {duplicates[:10]!r}; "
        f"tombstoned delta-store rows may be included twice "
        f"(once from compressed segment, once from delta B-tree)"
    )


@pytest.mark.fixture
def test_cs_mixed_compressed_row_values(fixture_bak_delta_rowgroup: Path) -> None:
    """Spot-check compressed rows: id=1 → val=1, id=50 → val=50, id=100 → val=100."""
    rows = _read_table(fixture_bak_delta_rowgroup, "cs_mixed")
    by_id = {r["id"]: r for r in rows}
    for check_id, expected_val in [(1, 1), (50, 50), (100, 100)]:
        assert check_id in by_id, f"compressed row id={check_id} missing from cs_mixed"
        actual_val = by_id[check_id]["val"]
        assert actual_val == expected_val, (
            f"cs_mixed id={check_id}: expected val={expected_val}, got {actual_val!r}"
        )


@pytest.mark.fixture
def test_cs_mixed_delta_row_values(fixture_bak_delta_rowgroup: Path) -> None:
    """Spot-check delta rows: val = id * 10 (e.g. id=101 → val=1010, id=150 → val=1500)."""
    rows = _read_table(fixture_bak_delta_rowgroup, "cs_mixed")
    by_id = {r["id"]: r for r in rows}
    for check_id, expected_val in [(101, 1010), (125, 1250), (150, 1500)]:
        assert check_id in by_id, (
            f"delta row id={check_id} missing from cs_mixed; "
            f"_read_columnstore_delta_rows may be returning 0 rows"
        )
        actual_val = by_id[check_id]["val"]
        assert actual_val == expected_val, (
            f"cs_mixed id={check_id}: expected val={expected_val}, got {actual_val!r}"
        )


# ---------------------------------------------------------------------------
# cs_delta_only: all rows in the open delta store, no compressed segment
# ---------------------------------------------------------------------------

@pytest.mark.fixture
def test_cs_delta_only_row_count(fixture_bak_delta_rowgroup: Path) -> None:
    """cs_delta_only must return all 30 rows (all from delta store, no segment)."""
    rows = _read_table(fixture_bak_delta_rowgroup, "cs_delta_only")
    assert len(rows) == CS_DELTA_ONLY_ROWS, (
        f"expected {CS_DELTA_ONLY_ROWS} rows in cs_delta_only, got {len(rows)}; "
        f"delta-store-only CCI may not be read correctly when no compressed segment exists"
    )


@pytest.mark.fixture
def test_cs_delta_only_row_values(fixture_bak_delta_rowgroup: Path) -> None:
    """Spot-check cs_delta_only: id=1 → val=1, id=15 → val=15, id=30 → val=30."""
    rows = _read_table(fixture_bak_delta_rowgroup, "cs_delta_only")
    by_id = {r["id"]: r for r in rows}
    for check_id in [1, 15, 30]:
        assert check_id in by_id, f"cs_delta_only id={check_id} missing"
        actual_val = by_id[check_id]["val"]
        assert actual_val == check_id, (
            f"cs_delta_only id={check_id}: expected val={check_id}, got {actual_val!r}"
        )


@pytest.mark.fixture
def test_cs_delta_only_no_duplicates(fixture_bak_delta_rowgroup: Path) -> None:
    """No duplicate rows in cs_delta_only — each id appears exactly once."""
    rows = _read_table(fixture_bak_delta_rowgroup, "cs_delta_only")
    ids = [r["id"] for r in rows]
    duplicates = sorted({i for i in ids if ids.count(i) > 1})
    assert not duplicates, (
        f"Duplicate ids in cs_delta_only: {duplicates[:10]!r}"
    )
