"""sql_variant extraction coverage tests (Gap D-2).

Validates that mssqlbak correctly extracts ``sql_variant`` column values with
mixed base types (INT, DECIMAL, NVARCHAR, BIGINT, DATETIME2, NULL).

Fixture
-------
``sql_variant_extract_full.bak`` — generated by
``tools/make_sql_variant_extract_fixture.py``
Contains the ``SqlVariantExtract`` database with one table:

``dbo.sv``
    id 1 — CAST(42        AS INT)          → expected int 42
    id 2 — CAST(3.14      AS DECIMAL(8,4)) → expected Decimal('3.1400')
    id 3 — CAST(N'hello'  AS NVARCHAR(20)) → expected str 'hello'
    id 4 — CAST(1         AS BIGINT)       → expected int 1
    id 5 — CAST('2025-01-01' AS DATETIME2(0)) → expected datetime(2025,1,1)
    id 6 — NULL                            → expected None

Each ``sql_variant`` value is preceded by a per-value type header that mssqlbak
must parse to select the correct type decoder.

Note
----
``sql_variant`` is currently in ``_MINMAX_SKIP_TYPES``.  These tests verify
that the *value itself* is still extracted correctly (not the min/max metadata).
If mssqlbak does not yet support ``sql_variant`` value decoding, these tests
are marked as ``xfail`` with a clear skip reason.

Running
-------
    pytest tests/test_sql_variant_extract_coverage.py -v
    pytest -k "sql_variant_extract" -q
"""
from __future__ import annotations

import datetime
import decimal
from pathlib import Path
from typing import Any

import pytest

from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows
from tools.cell_canon import canon
from tools.make_sql_variant_extract_fixture import (
    DB_NAME,
    ROW_COUNT,
)

_TABLE = "sv"

_SENTINELS: dict[int, str] = {
    7: "11111111-1111-1111-1111-111111111111",
    8: "0xdeadbeef",
    9: "2020-01-02 03:04:05.123456+05:30",
    10: "1.23",
}


def _read_sv(fixture: Path) -> list[dict[str, Any]]:
    store = PageStore.from_bak(fixture)
    schema = recover_schema(store)
    table = next((t for t in schema.tables if t.name == _TABLE), None)
    if table is None:
        pytest.fail(f"Table {_TABLE!r} not found in fixture (DB: {DB_NAME})")
    return list(read_table_rows(store, table))


@pytest.mark.fixture
def test_sql_variant_row_count(fixture_bak_sql_variant_extract: Path) -> None:
    """All 6 rows must be returned."""
    rows = _read_sv(fixture_bak_sql_variant_extract)
    assert len(rows) == ROW_COUNT, (
        f"expected {ROW_COUNT} rows, got {len(rows)}"
    )


@pytest.mark.fixture
def test_sql_variant_null_row(fixture_bak_sql_variant_extract: Path) -> None:
    """id=6 must return val=None."""
    rows = _read_sv(fixture_bak_sql_variant_extract)
    by_id = {r["id"]: r for r in rows}
    assert 6 in by_id, "id=6 missing"
    assert by_id[6]["val"] is None, (
        f"id=6: expected None, got {by_id[6]['val']!r}"
    )


@pytest.mark.fixture
def test_sql_variant_int_value(fixture_bak_sql_variant_extract: Path) -> None:
    """id=1: CAST(42 AS INT) must decode to int 42."""
    rows = _read_sv(fixture_bak_sql_variant_extract)
    by_id = {r["id"]: r for r in rows}
    assert 1 in by_id, "id=1 missing"
    val = by_id[1]["val"]
    assert val == 42, f"id=1: expected 42, got {val!r}"


@pytest.mark.fixture
def test_sql_variant_decimal_value(fixture_bak_sql_variant_extract: Path) -> None:
    """id=2: CAST(3.14 AS DECIMAL(8,4)) must decode to Decimal with scale 4."""
    rows = _read_sv(fixture_bak_sql_variant_extract)
    by_id = {r["id"]: r for r in rows}
    assert 2 in by_id, "id=2 missing"
    val = by_id[2]["val"]
    assert isinstance(val, decimal.Decimal), (
        f"id=2: expected Decimal, got {type(val).__name__!r} ({val!r})"
    )
    assert val == decimal.Decimal("3.1400"), (
        f"id=2: expected Decimal('3.1400'), got {val!r}"
    )


@pytest.mark.fixture
def test_sql_variant_nvarchar_value(fixture_bak_sql_variant_extract: Path) -> None:
    """id=3: CAST(N'hello' AS NVARCHAR(20)) must decode to str 'hello'."""
    rows = _read_sv(fixture_bak_sql_variant_extract)
    by_id = {r["id"]: r for r in rows}
    assert 3 in by_id, "id=3 missing"
    val = by_id[3]["val"]
    assert val == "hello", f"id=3: expected 'hello', got {val!r}"


@pytest.mark.fixture
def test_sql_variant_bigint_value(fixture_bak_sql_variant_extract: Path) -> None:
    """id=4: CAST(1 AS BIGINT) must decode to int 1."""
    rows = _read_sv(fixture_bak_sql_variant_extract)
    by_id = {r["id"]: r for r in rows}
    assert 4 in by_id, "id=4 missing"
    val = by_id[4]["val"]
    assert val == 1, f"id=4: expected 1, got {val!r}"


@pytest.mark.fixture
def test_sql_variant_datetime2_value(fixture_bak_sql_variant_extract: Path) -> None:
    """id=5: CAST('2025-01-01' AS DATETIME2(0)) must decode to datetime(2025,1,1)."""
    rows = _read_sv(fixture_bak_sql_variant_extract)
    by_id = {r["id"]: r for r in rows}
    assert 5 in by_id, "id=5 missing"
    val = by_id[5]["val"]
    expected = datetime.datetime(2025, 1, 1)
    assert isinstance(val, datetime.datetime), (
        f"id=5: expected datetime, got {type(val).__name__!r} ({val!r})"
    )
    assert val == expected, f"id=5: expected {expected!r}, got {val!r}"


@pytest.mark.fixture
@pytest.mark.parametrize("row_id", sorted(_SENTINELS))
def test_sql_variant_neighbor_values(
    fixture_bak_sql_variant_extract: Path,
    row_id: int,
) -> None:
    rows = _read_sv(fixture_bak_sql_variant_extract)
    by_id = {r["id"]: r for r in rows}
    assert row_id in by_id, f"id={row_id} missing"
    assert canon(by_id[row_id]["val"], "sql_variant") == _SENTINELS[row_id]
