"""Boundary-value regression tests for datetime / bit / decimal CCI encoding (Gap K-2).

Each parametrised test reads one table from the datetime boundary fixture and
checks that the labeled rows (min, max, sec_min/sec_max or equivalent, null)
decode to their expected Python values.

Fixture
-------
``tests/fixtures/boundarycoverage_datetime_full.bak`` — generated by
``tools/make_boundary_datetime_fixture.py``.  Each table has 1 200 rows so SQL
Server uses enc=4 compression in the clustered columnstore index.

Types covered (Gap K-2)
-----------------------
* ``bit``          — boolean bitpack; two non-null values + NULL
* ``decimal(9,4)`` — int32-backed scaled integer; 32-bit min/max boundary
* ``decimal(18,4)``— int64-backed scaled integer; 64-bit min/max boundary
* ``date``         — 3-byte days since 0001-01-01; epoch and max-date boundary
* ``datetime``     — 8-byte classic format; 1/300 s tick precision boundary
* ``datetime2(3)`` — millisecond precision; exact Python round-trip
* ``time(3)``      — time-of-day with millisecond precision
* ``smalldatetime``— 4-byte minutes + days since 1900-01-01
* ``datetimeoffset(3)`` — datetime2 + UTC offset; ±14 h offset boundary

Critical regression cases
--------------------------
``datetime`` min/max
    Classic datetime uses signed int32 days from 1900-01-01 (can be negative for
    dates before 1900).  The minimum value 1753-01-01 uses a large negative
    days value; an arithmetic error or sign error produces a wrong date.

    The 1/300 s tick precision is returned by SQL Server rounded to whole
    milliseconds (.000/.003/.007), so the maximum fractional value (299 ticks)
    decodes to 997 000 µs (.997), matching what any SQL Server client reads.

``date`` min/max
    Days=0 maps to 0001-01-01; days=3 652 058 maps to 9999-12-31.  Any
    off-by-one in the epoch calculation produces a wrong date.

``decimal(9,4)`` / ``decimal(18,4)``
    CCI enc=4 stores scaled-integer segments.  At the extremes of the type
    range (±99 999.9999 for p=9), an overflow in the CCI delta calculation
    (max - min) would corrupt the decoded value.

``datetimeoffset`` timezone boundaries
    The ±14 h offset (±840 minutes) is the maximum valid DATETIMEOFFSET offset.
    The decoded Python value must carry the original offset as its ``tzinfo``
    and show the original wall-clock time, not UTC.

Running
-------
    pytest tests/test_boundary_datetime_coverage.py -q
    pytest -k "test_boundary_datetime" -q
"""
from __future__ import annotations

import datetime as dt
from pathlib import Path
from typing import Any

import pytest

from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows
from tools.boundary_datetime_matrix import BOUNDARY_DATETIME_CASES, BoundaryCase


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _decode_table(fixture: Path, tbl_name: str) -> dict[str, Any]:
    """Read *tbl_name* from *fixture*; return ``{label: value}`` for labeled rows."""
    store = PageStore.from_bak(fixture)
    schema = recover_schema(store)
    table = next((t for t in schema.tables if t.name == tbl_name), None)
    if table is None:
        pytest.fail(f"Table {tbl_name!r} not found in fixture")
    result: dict[str, Any] = {}
    for row in read_table_rows(store, table):
        label: str | None = row.get("label")
        if label is not None:
            result[label] = row.get("v")
    return result


# ---------------------------------------------------------------------------
# Parametrised test
# ---------------------------------------------------------------------------

PARAMS = BOUNDARY_DATETIME_CASES
IDS = [c.name for c in PARAMS]


@pytest.mark.fixture
@pytest.mark.parametrize("case", PARAMS, ids=IDS)
def test_boundary_datetime(
    fixture_bak_boundary_datetime: Path, case: BoundaryCase
) -> None:
    """Every labeled boundary row decodes to its expected Python value."""
    tbl_name = f"tb_{case.name}"
    decoded = _decode_table(fixture_bak_boundary_datetime, tbl_name)

    for row in case.rows:
        assert row.label in decoded, (
            f"{tbl_name}: label {row.label!r} not found "
            f"(available: {sorted(decoded)})"
        )
        actual = decoded[row.label]

        if row.value is None:
            assert actual is None, (
                f"{case.name}[{row.label}]: expected None, got {actual!r}"
            )
        elif isinstance(row.value, dt.datetime) and row.value.tzinfo is not None:
            # Timezone-aware: compare wall-clock time AND UTC offset.
            assert isinstance(actual, dt.datetime) and actual.tzinfo is not None, (
                f"{case.name}[{row.label}]: expected tz-aware datetime, got {actual!r}"
            )
            assert actual == row.value, (
                f"{case.name}[{row.label}]: expected {row.value!r}, got {actual!r}"
            )
        else:
            assert actual == row.value, (
                f"{case.name}[{row.label}]: expected {row.value!r}, got {actual!r}"
            )
