"""CCI REORGANIZE + deleted-row bitmap coverage tests (Gap C-10).

Validates that mssqlbak correctly handles deleted rows in CCI compressed
rowgroups, both before and after ``REORGANIZE``.

Fixture
-------
``cci_reorganize_full.bak`` — generated by ``tools/make_cci_reorganize_fixture.py``
Contains the ``CciReorganize`` database with two tables:

``dbo.cci_deleted_no_reorg``
    1,200 rows inserted and compressed into a rowgroup, then 200 rows deleted
    (rows where id % 6 == 0).  NO subsequent REORGANIZE.
    The segment still physically contains 1,200 rows; deleted rows are tracked
    via a delete-indicator bitmap in the catalog.
    Expected live rows: 1,000.

``dbo.cci_deleted_reorg``
    Same data pattern, but REORGANIZE is run after the DELETE.  The segment is
    compacted to exactly 1,000 rows; the delete bitmap is cleared.
    Expected live rows: 1,000.

Critical regression path
------------------------
For ``cci_deleted_no_reorg``:
    mssqlbak must check the per-rowgroup delete bitmap (stored in the catalog)
    to exclude the 200 deleted rows from the 1,200-row segment.  Without this
    check it over-counts by 200 (returns 1,200 instead of 1,000).

For ``cci_deleted_reorg``:
    After REORGANIZE the segment is physically compacted.  mssqlbak must simply
    read the compacted 1,000-row segment.

Running
-------
    pytest tests/test_cci_reorganize_coverage.py -v
    pytest -k "cci_reorganize" -q
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows
from tools.make_cci_reorganize_fixture import (
    DB_NAME,
    DELETED_MOD,
    LIVE_COUNT,
    TOTAL_INSERTED,
)

_TABLE_NO_REORG = "cci_deleted_no_reorg"
_TABLE_REORG    = "cci_deleted_reorg"


def _read_table(fixture: Path, table_name: str) -> list[dict[str, Any]]:
    store = PageStore.from_bak(fixture)
    schema = recover_schema(store)
    table = next((t for t in schema.tables if t.name == table_name), None)
    if table is None:
        pytest.fail(f"Table {table_name!r} not found in fixture (DB: {DB_NAME})")
    return list(read_table_rows(store, table))


# ---------------------------------------------------------------------------
# cci_deleted_no_reorg: deleted rows tracked via delete bitmap
# ---------------------------------------------------------------------------

@pytest.mark.fixture
def test_cci_deleted_no_reorg_live_count(fixture_bak_cci_reorganize: Path) -> None:
    """cci_deleted_no_reorg must return LIVE_COUNT rows, not TOTAL_INSERTED.

    This is the core C-10 assertion: without delete-bitmap support mssqlbak
    over-counts by 200, returning 1,200 instead of 1,000.
    """
    rows = _read_table(fixture_bak_cci_reorganize, _TABLE_NO_REORG)
    assert len(rows) == LIVE_COUNT, (
        f"expected {LIVE_COUNT} live rows in {_TABLE_NO_REORG!r}, "
        f"got {len(rows)}; "
        f"delete bitmap may not be checked — deleted rows included in count"
    )


@pytest.mark.fixture
def test_cci_deleted_no_reorg_deleted_ids_absent(fixture_bak_cci_reorganize: Path) -> None:
    """Deleted ids (id % 6 == 0) must not appear in cci_deleted_no_reorg."""
    rows = _read_table(fixture_bak_cci_reorganize, _TABLE_NO_REORG)
    deleted_ids_found = [r["id"] for r in rows if r["id"] % DELETED_MOD == 0]
    assert not deleted_ids_found, (
        f"Deleted row ids found in {_TABLE_NO_REORG!r}: "
        f"{deleted_ids_found[:10]!r}; delete bitmap not applied"
    )


@pytest.mark.fixture
def test_cci_deleted_no_reorg_live_ids_present(fixture_bak_cci_reorganize: Path) -> None:
    """All live ids (id % 6 != 0) must be present in cci_deleted_no_reorg."""
    rows = _read_table(fixture_bak_cci_reorganize, _TABLE_NO_REORG)
    present_ids = {r["id"] for r in rows}
    expected_live = {i for i in range(1, TOTAL_INSERTED + 1) if i % DELETED_MOD != 0}
    missing = expected_live - present_ids
    assert not missing, (
        f"{len(missing)} live rows missing from {_TABLE_NO_REORG!r}: "
        f"{sorted(missing)[:10]!r}"
    )


# ---------------------------------------------------------------------------
# cci_deleted_reorg: segment compacted via REORGANIZE after delete
# ---------------------------------------------------------------------------

@pytest.mark.fixture
def test_cci_deleted_reorg_live_count(fixture_bak_cci_reorganize: Path) -> None:
    """cci_deleted_reorg (post-REORGANIZE) must return exactly LIVE_COUNT rows."""
    rows = _read_table(fixture_bak_cci_reorganize, _TABLE_REORG)
    assert len(rows) == LIVE_COUNT, (
        f"expected {LIVE_COUNT} rows in {_TABLE_REORG!r} (post-REORGANIZE), "
        f"got {len(rows)}"
    )


@pytest.mark.fixture
def test_cci_deleted_reorg_deleted_ids_absent(fixture_bak_cci_reorganize: Path) -> None:
    """Deleted ids must not appear in cci_deleted_reorg after REORGANIZE."""
    rows = _read_table(fixture_bak_cci_reorganize, _TABLE_REORG)
    deleted_ids_found = [r["id"] for r in rows if r["id"] % DELETED_MOD == 0]
    assert not deleted_ids_found, (
        f"Deleted row ids found in {_TABLE_REORG!r} after REORGANIZE: "
        f"{deleted_ids_found[:10]!r}"
    )


@pytest.mark.fixture
def test_cci_deleted_reorg_spot_check(fixture_bak_cci_reorganize: Path) -> None:
    """Spot-check cci_deleted_reorg: val = id * 10 for sampled live rows."""
    rows = _read_table(fixture_bak_cci_reorganize, _TABLE_REORG)
    by_id = {r["id"]: r for r in rows}
    # Check a few live rows (id % 6 != 0)
    for check_id in [1, 5, 7, 11, 100, 1_199]:
        if check_id % DELETED_MOD == 0:
            continue
        assert check_id in by_id, f"live row id={check_id} missing"
        expected_val = check_id * 10
        actual = by_id[check_id]["val"]
        assert actual == expected_val, (
            f"{_TABLE_REORG!r} id={check_id}: expected val={expected_val}, got {actual!r}"
        )
