"""Gap D-6 — Native JSON column type (SS2025 only).

The native JSON type (SS2025, type_id 244) stores JSON in a proprietary
binary encoding on disk — NOT as a plain UTF-8 or UCS-2 string.  The on-disk
format is a 2-byte header followed by a binary JSON representation that embeds
field names and string values as UTF-8 substrings but is not directly
parseable as JSON text.

mssqlbak decodes native JSON columns to their canonical compact text form.

Key guarantees tested here:
  1. read_table_rows returns the correct row count without raising.
  2. Every `doc` value is text, not bytes.
  3. The decoded text matches the JSON emitted by SQL Server.
  4. The decoded documents remain distinct.

Fixture: ``native_json_full.bak`` (SS2025 fixture directory only)
Generated by: ``python -m tools.fixture_run all-versions --suite native-json --version 2025``
"""

from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows


def test_native_json_row_count(fixture_bak_native_json: str) -> None:
    from tools.make_native_json_fixture import ROW_COUNT, TABLE

    store = PageStore.from_bak(fixture_bak_native_json)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None, f"table {TABLE!r} not found"
    rows = list(read_table_rows(store, tbl))
    assert len(rows) == ROW_COUNT


def test_native_json_returns_text(fixture_bak_native_json: str) -> None:
    """Every doc column value is decoded to canonical JSON text."""
    from tools.make_native_json_fixture import TABLE

    store = PageStore.from_bak(fixture_bak_native_json)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None

    for row in read_table_rows(store, tbl):
        doc = row.get("doc")
        assert doc is not None, f"id={row['id']}: doc is None"
        assert isinstance(doc, str), f"id={row['id']}: expected str, got {type(doc).__name__}"
        assert len(doc) > 0, f"id={row['id']}: doc is empty bytes"


def test_native_json_text_matches_expected_docs(fixture_bak_native_json: str) -> None:
    """Decoded native JSON text matches SQL Server's textual representation."""
    from tools.make_native_json_fixture import KNOWN_DOCS, TABLE

    store = PageStore.from_bak(fixture_bak_native_json)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None

    rows_by_id = {r["id"]: r for r in read_table_rows(store, tbl)}
    for row_id, _inserted, expected in KNOWN_DOCS:
        assert rows_by_id[row_id]["doc"] == expected


def test_native_json_distinct_docs(fixture_bak_native_json: str) -> None:
    """Every row must have a distinct decoded JSON document."""
    from tools.make_native_json_fixture import ROW_COUNT, TABLE

    store = PageStore.from_bak(fixture_bak_native_json)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None

    docs = [r["doc"] for r in read_table_rows(store, tbl)]
    assert len(docs) == ROW_COUNT
    assert len(set(docs)) == ROW_COUNT, "some rows have identical JSON text"
