"""Tests for striped (multi-file) backup parsing via PageStore.from_stripe.

Fixture: tests/fixtures_2022/striped_full_{1,2}.bak and striped_single.bak
Generated by: python -m tools.fixture_run stripe
"""
from __future__ import annotations

import os
import pytest
from pathlib import Path

from mssqlbak.pages import AnyPageStore, PageStore
from mssqlbak.catalog import recover_schema
from mssqlbak.rows import read_table_rows

FIXTURE_DIR = Path(os.environ.get("FIXTURE_DIR", str(Path(__file__).parent / "fixtures_2022")))
STRIPE1 = FIXTURE_DIR / "striped_full_1.bak"
STRIPE2 = FIXTURE_DIR / "striped_full_2.bak"
SINGLE = FIXTURE_DIR / "striped_single.bak"


@pytest.fixture(scope="module")
def stripe_store() -> AnyPageStore:
    return PageStore.from_stripe([STRIPE1, STRIPE2])


@pytest.fixture(scope="module")
def single_store() -> AnyPageStore:
    return PageStore.from_bak(SINGLE)


def test_stripe_fixtures_exist() -> None:
    for path in (STRIPE1, STRIPE2, SINGLE):
        assert path.exists(), f"fixture missing: {path.name}"


def test_stripe_page_count_nonzero(stripe_store: AnyPageStore) -> None:
    assert stripe_store.page_count > 0


def test_stripe_same_page_count_as_single(
    stripe_store: AnyPageStore, single_store: AnyPageStore
) -> None:
    assert stripe_store.page_count == single_store.page_count


def test_stripe_same_schema_as_single(
    stripe_store: AnyPageStore, single_store: AnyPageStore
) -> None:
    stripe_tables = {t.name for t in recover_schema(stripe_store).tables}
    single_tables = {t.name for t in recover_schema(single_store).tables}
    assert stripe_tables == single_tables


def test_stripe_rows_match_single(
    stripe_store: AnyPageStore, single_store: AnyPageStore
) -> None:
    stripe_schema = recover_schema(stripe_store)
    single_schema = recover_schema(single_store)

    probe_stripe = next(t for t in stripe_schema.tables if t.name == "probe")
    probe_single = next(t for t in single_schema.tables if t.name == "probe")

    rows_stripe = list(read_table_rows(stripe_store, probe_stripe))
    rows_single = list(read_table_rows(single_store, probe_single))

    assert len(rows_stripe) == 20
    assert rows_stripe == rows_single


def test_stripe_row_values(stripe_store: PageStore) -> None:
    schema = recover_schema(stripe_store)
    probe = next(t for t in schema.tables if t.name == "probe")
    rows = list(read_table_rows(stripe_store, probe))

    assert rows[0] == {"id": 1, "label": "row1", "score": pytest.approx(1.1), "flag": True}
    assert rows[9] == {"id": 10, "label": "row10", "score": pytest.approx(11.0), "flag": False}
    assert rows[19]["id"] == 20
    assert rows[19]["flag"] == False  # noqa: E712  (20 % 2 == 0)
