"""Boundary-value regression tests for large-row-group columnstore encoding.

Each parametrised test reads one table from the boundary fixture and checks
that the labeled rows (min, max, sec_min, sec_max, zero/mid, null) decode to
their expected Python values.

Fixture
-------
``tests/fixtures/boundarycoverage_full.bak`` — generated by
``tools/make_boundary_fixture.py``.  Each table has 1 200 rows so SQL Server
uses enc=4 compression in the clustered columnstore index.

Critical regression cases
--------------------------
bigint / money with their absolute minimum values
    enc=4 uses 2^63 as the null sentinel (instead of 0) when ``mn == INT64_MIN``.
    With the previous 4-row tabletypecoverage fixture the type used enc=1 and
    the bug was invisible; this fixture forces enc=4 where the fix matters.

second-to-MIN / second-to-MAX for all numeric types
    Validates the ``mn + (stored − 1) × magnitude`` formula has no off-by-one
    errors at the extreme ends of every numeric range.

Running
-------
    pytest tests/test_boundary_coverage.py -q
    pytest -k "test_boundary_bigint" -q
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows
from tools.boundary_matrix import BOUNDARY_CASES, BoundaryCase


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _decode_table(fixture: Path, tbl_name: str) -> dict[str, Any]:
    """Read *tbl_name* from *fixture* and return ``{label: v}`` for labeled rows."""
    store = PageStore.from_bak(fixture)
    schema = recover_schema(store)
    table = next((t for t in schema.tables if t.name == tbl_name), None)
    if table is None:
        pytest.fail(f"Table {tbl_name!r} not found in fixture")
    result: dict[str, Any] = {}
    for row in read_table_rows(store, table):
        label: str | None = row.get("label")
        if label is not None:
            result[label] = row.get("v")
    return result


# ---------------------------------------------------------------------------
# Parametrised test
# ---------------------------------------------------------------------------

PARAMS = BOUNDARY_CASES
IDS = [c.name for c in PARAMS]


@pytest.mark.fixture
@pytest.mark.parametrize("case", PARAMS, ids=IDS)
def test_boundary(fixture_bak_boundary: Path, case: BoundaryCase) -> None:
    """Every labeled boundary row decodes to its expected Python value."""
    tbl_name = f"tb_{case.name}"
    decoded = _decode_table(fixture_bak_boundary, tbl_name)

    for row in case.rows:
        assert row.label in decoded, (
            f"{tbl_name}: label {row.label!r} not found "
            f"(available: {sorted(decoded)})"
        )
        actual = decoded[row.label]
        if row.value is None:
            assert actual is None, (
                f"{case.name}[{row.label}]: expected None, got {actual!r}"
            )
        else:
            assert actual == row.value, (
                f"{case.name}[{row.label}]: expected {row.value!r}, got {actual!r}"
            )
