"""Gap E-4 — Spatial index internal tessellation table.

A SPATIAL INDEX creates an internal tessellation B-tree (sysschobjs.type = 'IT').
recover_schema must skip it and return only the user geometry table.
read_table_rows must return the original geometry rows without crash.

Fixture: ``spatial_index_full.bak``
Generated by: ``python -m tools.fixture_run all-versions --suite spatial-index``
"""
from mssqlbak.catalog import recover_schema
from mssqlbak.pages import PageStore
from mssqlbak.rows import read_table_rows


def test_spatial_index_no_internal_tables(fixture_bak_spatial_index: str) -> None:
    """recover_schema must not expose internal spatial tessellation tables."""
    store = PageStore.from_bak(fixture_bak_spatial_index)
    schema = recover_schema(store)

    # Internal spatial index tables have names like sys_spatial_index_tessellation_...
    for tbl in schema.tables:
        assert not tbl.name.startswith("sys_spatial_index"), (
            f"Internal spatial tessellation table {tbl.name!r} must not be in schema"
        )


def test_spatial_index_user_table_present(fixture_bak_spatial_index: str) -> None:
    from tools.make_spatial_index_fixture import TABLE

    store = PageStore.from_bak(fixture_bak_spatial_index)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None, f"user table {TABLE!r} not found in schema"


def test_spatial_index_row_count(fixture_bak_spatial_index: str) -> None:
    from tools.make_spatial_index_fixture import ROW_COUNT, TABLE

    store = PageStore.from_bak(fixture_bak_spatial_index)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None

    rows = list(read_table_rows(store, tbl))
    assert len(rows) == ROW_COUNT


def test_spatial_index_values(fixture_bak_spatial_index: str) -> None:
    """name column follows 'pt_N' pattern; loc column is not None."""
    from tools.make_spatial_index_fixture import TABLE

    store = PageStore.from_bak(fixture_bak_spatial_index)
    schema = recover_schema(store)
    tbl = next((t for t in schema.tables if t.name == TABLE), None)
    assert tbl is not None

    rows_by_id = {r["id"]: r for r in read_table_rows(store, tbl)}

    for sample_id in [1, 50, 100, 150, 200]:
        row = rows_by_id.get(sample_id)
        assert row is not None, f"row id={sample_id} missing"
        assert row["name"] == f"pt_{sample_id}", f"id={sample_id}: {row['name']!r}"
        # loc is a geometry value — at minimum it must not be None
        assert row["loc"] is not None, f"id={sample_id}: loc is None"
