"""Partial stubs for pyarrow.compute.

pyarrow registers most compute functions dynamically at import time, so they are
absent from the shipped compute.py and therefore invisible to pyright.  This stub
declares only the functions actually used in this project; all signatures are
intentionally broad (accept any / return any) so pyright does not second-guess the
runtime behaviour while still resolving the attribute-access errors.
"""

from typing import Any

# ── casting / type conversion ────────────────────────────────────────────────
def cast(arr: Any, target_type: Any, safe: bool = ..., options: Any = ..., memory_pool: Any = ...) -> Any: ...

# ── null handling ────────────────────────────────────────────────────────────
def drop_null(values: Any) -> Any: ...
def fill_null(values: Any, fill_value: Any) -> Any: ...
def is_null(values: Any, nan_is_null: bool = ...) -> Any: ...

# ── comparisons ──────────────────────────────────────────────────────────────
def equal(x: Any, y: Any) -> Any: ...
def not_equal(x: Any, y: Any) -> Any: ...

# ── boolean / logical ────────────────────────────────────────────────────────
def and_(x: Any, y: Any) -> Any: ...
def or_(x: Any, y: Any) -> Any: ...
def invert(values: Any) -> Any: ...
def if_else(condition: Any, true_values: Any, false_values: Any) -> Any: ...

# ── aggregation ──────────────────────────────────────────────────────────────
def sum(array: Any, skip_nulls: bool = ..., min_count: int = ..., options: Any = ..., memory_pool: Any = ...) -> Any: ...

# ── reordering / indexing ────────────────────────────────────────────────────
def sort_indices(values: Any, sort_keys: Any = ..., null_placement: str = ...) -> Any: ...
def take(data: Any, indices: Any, boundscheck: bool = ..., memory_pool: Any = ...) -> Any: ...

# ── string functions ─────────────────────────────────────────────────────────
def utf8_lower(strings: Any) -> Any: ...
def utf8_upper(strings: Any) -> Any: ...
def utf8_ltrim(strings: Any, characters: str) -> Any: ...
def utf8_rtrim(strings: Any, characters: str) -> Any: ...
def utf8_trim(strings: Any, characters: str) -> Any: ...
